### ISSUE TITLE
bug on migration when using mysql

### ISSUE THREAD

**Issue by gabelula** [stefanw/froide#140]
When setting up froide (for the first time) with mysql
When running

$ python manage.py syncdb --noinput --migrate

https://gist.github.com/gabelula/63ecd3f5edf85e172f11

```
Running migrations for foirequest:
 - Migrating forwards to 0034_auto__add_field_deferredmessage_spam.
 > account:0001_initial
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 254, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 113, in run
    dry_run.run_migration(migration, database)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 190, in run_migration
    self._run_migration(migration)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 177, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0001_initial'! Aborting.
Traceback (most recent call last):
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 174, in _run_migration
    migration_function()
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/var/www/dp-abreinfo/froide/account/migrations/0001_initial.py", line 27, in forwards
    ('username', self.gf('django.db.models.fields.CharField')(**{'unique': 'True', 'max_length': '30'}))
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/db/generic.py", line 356, in create_table
    for field_name, field in fields
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/db/generic.py", line 665, in column_sql
    field = self._field_sanity(field)
  File "/home/dp-abreinfo/froidenv/lib/python2.6/site-packages/south/db/mysql.py", line 273, in _field_sanity
    type = self._db_type_for_alter_column(field).lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by stefanw** [comment]
Mh, not sure what went wrong, but we moved on from South, so closing.
