### ISSUE TITLE
new development setup fails so import publicbody.json

### ISSUE THREAD

**Issue by g0ldfisch** [stefanw/froide#149]
Did a checkout of Commit  9af15f87c2 and setup the environment according to getting started guide (http://froide.readthedocs.org/en/latest/gettingstarted/). When trying to import sample data from publicbodies.json import fails with the following output:
***
$python manage.py loaddata publicbody.json
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 55, in handle
    self.loaddata(fixture_labels)
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 84, in loaddata
    self.load_label(fixture_label)
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 134, in load_label
    for obj in objects:
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/serializers/json.py", line 76, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/serializers/python.py", line 90, in Deserializer
    Model = _get_model(d["model"])
  File "/usr/home/gf/projects/okf_froide/.froide_env/lib/python2.7/site-packages/django/core/serializers/python.py", line 153, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/usr/home/gf/projects/okf_froide/froide/publicbody/fixtures/publicbody.json': Invalid model identifier: 'publicbody.publicbodytopic'

**Comment by joelpurra** [comment]
The still problem exists in 1616bb5debad0e85410b53a9ed16e0ee7c74b7b8 from 2015-08-21.

**Comment by stefanw** [comment]
Try passing `--no-initial-data` to migrate. I'll have another look.

**Comment by fin** [comment]
pull request here: https://github.com/stefanw/froide/pull/155

**Comment by joelpurra** [comment]
@fin: thanks for the fix!

**Comment by mattiasaxell** [comment]
@fin @joelpurra does this fix the problem that @robinharms sent an e-mail about with importscript to populate the site?
"The "Add basic database objects" fails since it seems like one of the models have moved or changed: python manage.py loaddata publicbody.json"

**Comment by joelpurra** [comment]
@mattiasaxell wrote:
> @fin @joelpurra does this fix the problem that @robinharms sent an e-mail about with importscript to populate the site?

While I haven't really dug into the contents of [`publicbody.json`](https://raw.githubusercontent.com/stefanw/froide/master/froide/publicbody/fixtures/publicbody.json), I assume it's all editable through the user interface. It's just sample data that can be skipped when setting things up manually.

**Comment by mattiasaxell** [comment]
@joelpurra Yes it seems editable. Yes, that's what I understand as well too now. :) thanks for checking!
