### ISSUE TITLE
libmagic is a requirement, but not installed

### ISSUE THREAD

**Issue by pdehaye** [stefanw/froide#150]
I tried the instructions here:
http://froide.readthedocs.org/en/latest/gettingstarted/
but this failed when accessing the http://127.0.0.1:8000/ address with the following message:
A server error occurred.  Please contact the administrator.
The log has this:
(froide-env)*:froide pdehaye$ python manage.py runserver
django-configurations version 0.8, using configuration 'Dev'
Validating models...

0 errors found
June 17, 2015 - 01:22:42
Django version 1.6.9, using settings 'froide.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/pdehaye/Software/froide/froide/urls.py", line 22, in <module>
    from froide.foirequest.views import FoiRequestSitemap
  File "/Users/pdehaye/Software/froide/froide/foirequest/views.py", line 34, in <module>
    from .forms import (RequestForm, ConcreteLawForm, TagFoiRequestForm,
  File "/Users/pdehaye/Software/froide/froide/foirequest/forms.py", line 2, in <module>
    import magic
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/magic.py", line 161, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
[17/Jun/2015 01:23:22] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/pdehaye/Software/froide/froide/urls.py", line 22, in <module>
    from froide.foirequest.views import FoiRequestSitemap
  File "/Users/pdehaye/Software/froide/froide/foirequest/views.py", line 34, in <module>
    from .forms import (RequestForm, ConcreteLawForm, TagFoiRequestForm,
  File "/Users/pdehaye/Software/froide/froide/foirequest/forms.py", line 2, in <module>
    import magic
  File "/Users/pdehaye/Software/froide-env/lib/python2.7/site-packages/magic.py", line 161, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by stefanw** [comment]
Mh, please install libmagic. It's used to check uploaded files to see if they are in the right format.

If you think this shouldn't be a required dependency, we could think about binding this very late or making it optional. However, allowing the upload of any kind of file might not be a good idea.

**Comment by joelpurra** [comment]
@stefanw: noticed this as well. How about adding the required version of `libmagic` to `requirements.txt`?

**Comment by joelpurra** [comment]
I see now that `libmagic` isn't a python dependency, but a system command.
https://github.com/ahupp/python-magic#dependencies

Perhaps this should be documented then.

**Comment by stefanw** [comment]
Maybe the python-magic dependency should be optional. Although the error message above seems pretty clear to me.

**Comment by fin** [comment]
pull request for doc changes: https://github.com/stefanw/froide/pull/154

**Comment by joelpurra** [comment]
@fin: thanks for adding the link!
